# Generated by Django 4.1.3 on 2022-12-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_space_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_zone_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date_time', models.DateTimeField(auto_now_add=True)),
                ('release_date_time', models.DateTimeField(auto_now=True)),
                ('vehicle_registration_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parkingspace')),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parkingzone')),
            ],
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='parking_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parkingzone'),
        ),
    ]
