# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleparking',
            name='status',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(default='Vacant', max_length=15),
        ),
    ]
