# Generated by Django 4.1.3 on 2022-12-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_parkingspace_vehicle_parked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleparking',
            name='status',
            field=models.CharField(default='Parked', max_length=15),
        ),
    ]
